name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: neovim
        uses: rhysd/action-setup-vim@v1
        with:
          # apt neovim is too old
          neovim: true
          version: nightly # using vim.fs.joinpath
      - name: debug
        run: HOME=./home nvim --headless -c "echo &rtp" +qa
