name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: neovim
        uses: rhysd/action-setup-vim@v1
        with:
          # apt neovim is too old
          neovim: true
          # version: nightly
      - name: debug
        run: HOME=./home nvim --headless -c "echo &rtp" +qa
      - name: debug 2
        run: nvim --headless -c "echo &rtp" +qa
        env:
            HOME: ./home
      - name: mkdir
        run: |
          mkdir -p ~/.config/nvim ~/.local/share/nvim
          touch ~/.config/nvim/init.lua
      - name: debug 3
        run: HOME=./home nvim --headless -c "echo &rtp" +qa
      - name: debug 4
        run: nvim --headless -c "echo &rtp" +qa
      - name: debug 5
        run: HOME=./home nvim --headless -c "echo &rtp" +qa
